### PR TITLE
Changed PropagationFlags to 'None' which fixes #96

### LINKED ISSUE #96: A (new?) startup crash for me.
Only occurs on one machine:

Attempted to perform an unauthorized operation.

Exception Information:

```
   at System.Security.AccessControl.Win32.SetSecurityInfo(ResourceType type, String name, SafeHandle handle, SecurityInfos securityInformation, SecurityIdentifier owner, SecurityIdentifier group, GenericAcl sacl, GenericAcl dacl)
   at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, SafeHandle handle, AccessControlSections includeSections, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity.Persist(String fullPath)
   at System.IO.DirectoryInfo.SetAccessControl(DirectorySecurity directorySecurity)
   at MASGAU.Game.GameXmlFiles..ctor() in c:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\Game\GameXmlFiles.cs:line 99
   at MASGAU.Games.loadXml() in c:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\Game\Games.cs:line 206
   at MASGAU.Games.detectGames(List`1 these_games) in c:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\Game\Games.cs:line 261
   at MASGAU.Games.detectGames() in c:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\Game\Games.cs:line 236
   at MASGAU.Main.MainProgramHandler.detectGames() in c:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\AMainProgramHandler.cs:line 43
   at MASGAU.Main.MainProgramHandler.doWork(Object sender, DoWorkEventArgs e) in c:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\AMainProgramHandler.cs:line 38
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

```

I can click "send report" and it appears to have sent.
There is a small, blank masgau window, maybe 2" x 1", separate from the main window.

 I haven't done much troubleshooting yet - like all my systems, MASGAU 1.0.6 on Win 7x64, backup folder is SkyDrive sub-folder.

### PR DESCRIPTION
**Pull request by AdmiringWorm**
The PropagationFlags was incorrectly set, 'PropagationFlags.None' sets the correct permissions for the current folder, sub directories and their files.
'PropagationFlags.InheritOnly' just set the correct permissions for sub directories and the files.

### CODE REVIEW

**Comment by sanmadjack** [comment]
Is there documentation to back that up? I thought "None" meant it would set on the folder only.

**Comment by AdmiringWorm** [comment]
no documentations, just found that out using trial and error.

**Comment by sanmadjack** [comment]
Found the docs for that enum:

http://msdn.microsoft.com/en-us/library/system.security.accesscontrol.propagationflags(v=vs.110).aspx

Looks like the "None" setting is for when there are no inheritance flags set, which there are two set in this case. I'm willing to accept that this will resolve the issue, I just need proof that it allows the permissions to be set properly when previously they were not.

**Comment by AdmiringWorm** [comment]
So before the hotifx the following permissions are set on the different folders when the
program is run as an administrator.
image
If it is then later run in Single User mode it produces the following error log:

```
10.02.2014 15:05:52 - STRING AllUSersMode NOT FOUND
10.02.2014 15:05:52 - STRING AllUSersMode OF TYPE Source NOT FOUND
10.02.2014 15:05:52 - Error while attempting to reset xml folder permissions
10.02.2014 15:05:53 - 10.02.2014 15:05:52 - Attempted to perform an unauthorized operation.   at System.Security.AccessControl.Win32.SetSecurityInfo(ResourceType type, String name, SafeHandle handle, SecurityInfos securityInformation, SecurityIdentifier owner, SecurityIdentifier group, GenericAcl sacl, GenericAcl dacl)
   at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, SafeHandle handle, AccessControlSections includeSections, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity.Persist(String fullPath)
   at System.IO.DirectoryInfo.SetAccessControl(DirectorySecurity directorySecurity)
   at MASGAU.Game.GameXmlFiles..ctor() in d:\TeamCity\buildAgent\work\8517ea059cb9bd4e\MASGAU.Common\Game\GameXmlFiles.cs:line 103
```

and after the fix the permissions set are:
image

and produces no error file (except the missing strings)

**Comment by sanmadjack** [comment]
What about the files within the folder? Are their permissions set to allow everyone full control? 

Also, the missing string line is caused by this in the nb-NO.xml file:

  <string name="JumpMainProgramAllUsers" type="tooltip">Åpne MASGAU i %AllUSersMode%</string>

I went ahead and corrected the case. I might consider making it case-insensitive in the future.

**Comment by AdmiringWorm** [comment]
They successfully inherit the settings from the parent folder.
image

this is the permission set on q.xml

**Comment by AdmiringWorm** [comment]
BTW, you probably would want to fix the property name change of the HotKey in TranslationHelpers (project Translator.WPF) as well, they still reference the old name.

**Comment by sanmadjack** [comment]
Guess that's that then. If it works, then it works.

Could you be more specific about what you're seeing in TranslationHelpers? Maybe make an issue for it?

**Comment by sanmadjack** [comment]
Thanks much for figuring this out, btw.

**Comment by AdmiringWorm** [comment]
No problem, it was just by chance though.

About the TranslationHelpers I sent an email a couple of days back about it, but what I'm talking about
is the lines like this: https://github.com/sanmadjack/Translator.WPF.CSharp/blob/master/TranslationHelpers.cs#L173
not just that line of course but all of them in that file, since you changed the name in TranslateableString.cs:
https://github.com/sanmadjack/Translator.CSharp/commit/109f82ccd1b56df304c7999330ac4290296d1059#diff-db8a384a829864c85c95546dd627e4cdR13

**Comment by sanmadjack** [comment]
Ah, I see. Looks like the Translator commit I made got pushed, but the Translator.WPF didn't. I'll check things and make sure they get pushed.

**Pull request merged**
