### PR TITLE
Data

### PR DESCRIPTION
**Pull request by AdmiringWorm**

### CODE REVIEW

**Comment by sanmadjack** [comment]
On your last commit, I noticed that windows.xml says this:

5358 additions, 5161 deletions not shown

It's basically telling me the entire file changed. What happened?

**Comment by AdmiringWorm** [comment]
have no idea, maybe cause I opened it my vs2010 and it styled the xml after my settings or something. But I seriously have no idea, I was wondering about it as well

**Comment by sanmadjack** [comment]
I did a manual diff, looks like the indentations all got changed. Looks like it should be okay though. Try to be mindful of that in the future.

**Comment by sanmadjack** [comment]
Okay, everything looks good! I'm going to go ahead and pull now.

**Comment by AdmiringWorm** [comment]
I'm sorry, won't happen again

**Pull request merged**
